begin;

insert into public.programs (
  id,
  slug,
  title,
  subtitle,
  tags,
  start_date_label,
  duration_label,
  price_eur,
  image_url,
  is_featured
)
values
  ('PRG-2101', 'dev-blockchain', 'Dev Blockchain', 'Construire des dApps et smart contracts en production', array['Blockchain', 'Developpement', 'Security'], 'Mai 2026', '14 semaines', 6200, 'https://picsum.photos/seed/alyra-2101/640/360', true),
  ('PRG-2102', 'expert-blockchain', 'Expert Blockchain', 'Architecture protocoles, L1/L2 et securite avancee', array['Blockchain', 'Security', 'Gouvernance'], 'Juin 2026', '18 semaines', 7600, 'https://picsum.photos/seed/alyra-2102/640/360', true),
  ('PRG-2103', 'finance-decentralisee', 'Finance Decentralisee', 'Lending, AMM, tokenisation et gestion des risques', array['Blockchain', 'Finance', 'Product'], 'Juillet 2026', '12 semaines', 4900, 'https://picsum.photos/seed/alyra-2103/640/360', true),
  ('PRG-2104', 'consultant-intelligence-artificielle', 'Consultant Intelligence Artificielle', 'Cadrage IA, roadmap et transformation metier', array['IA', 'Product', 'Data'], 'Aout 2026', '10 semaines', 3900, 'https://picsum.photos/seed/alyra-2104/640/360', true),
  ('PRG-2105', 'developpeur-intelligence-artificielle', 'Developpeur Intelligence Artificielle', 'ML engineering, MLOps et applications generatives', array['IA', 'Developpement', 'Data'], 'Septembre 2026', '16 semaines', 6900, 'https://picsum.photos/seed/alyra-2105/640/360', true),
  ('PRG-2106', 'smart-contract-security', 'Smart Contract Security', 'Audit, tests d''intrusion et securisation Solidity', array['Blockchain', 'Security', 'Developpement'], 'Octobre 2026', '8 semaines', 3400, 'https://picsum.photos/seed/alyra-2106/640/360', false),
  ('PRG-2107', 'layer-2-engineering', 'Layer 2 Engineering', 'Scalabilite Ethereum, rollups et interop', array['Blockchain', 'Developpement', 'Security'], 'Novembre 2026', '12 semaines', 5600, 'https://picsum.photos/seed/alyra-2107/640/360', false),
  ('PRG-2108', 'dao-operations', 'DAO Operations', 'Gouvernance, operations et outillage communautaire', array['Blockchain', 'Gouvernance', 'Product'], 'Decembre 2026', '8 semaines', 3200, 'https://picsum.photos/seed/alyra-2108/640/360', false),
  ('PRG-2109', 'tokenomics-strategy', 'Tokenomics Strategy', 'Modeles economiques, incentives et gouvernance', array['Blockchain', 'Finance', 'Gouvernance'], 'Janvier 2027', '6 semaines', 2600, 'https://picsum.photos/seed/alyra-2109/640/360', false),
  ('PRG-2110', 'web3-fullstack', 'Web3 Fullstack', 'Front React, wallets et donnees on-chain', array['Blockchain', 'Developpement', 'Product'], 'Fevrier 2027', '14 semaines', 6400, 'https://picsum.photos/seed/alyra-2110/640/360', false),
  ('PRG-2111', 'data-analyst-on-chain', 'Data Analyst On-Chain', 'Monitoring protocoles et analytics blockchain', array['Blockchain', 'Data', 'Product'], 'Mars 2027', '8 semaines', 3300, 'https://picsum.photos/seed/alyra-2111/640/360', false),
  ('PRG-2112', 'blockchain-for-finance', 'Blockchain for Finance', 'Tokenisation d''actifs et usages institutionnels', array['Blockchain', 'Finance', 'Data'], 'Avril 2027', '10 semaines', 4600, 'https://picsum.photos/seed/alyra-2112/640/360', false),
  ('PRG-2113', 'generative-ai-studio', 'Generative AI Studio', 'RAG, agents IA et applications metier', array['IA', 'Developpement', 'Data'], 'Mai 2027', '10 semaines', 4900, 'https://picsum.photos/seed/alyra-2113/640/360', false),
  ('PRG-2114', 'ai-governance-ethics', 'AI Governance & Ethics', 'Conformite, risque et cadre de gouvernance IA', array['IA', 'Gouvernance', 'Security'], 'Juin 2027', '6 semaines', 2800, 'https://picsum.photos/seed/alyra-2114/640/360', false),
  ('PRG-2115', 'ai-for-product-managers', 'AI for Product Managers', 'Pilotage de produits IA et mesure de valeur', array['IA', 'Product', 'Data'], 'Juillet 2027', '6 semaines', 2500, 'https://picsum.photos/seed/alyra-2115/640/360', false),
  ('PRG-2116', 'cloud-for-ai-systems', 'Cloud for AI Systems', 'Architecture cloud, couts et observabilite', array['IA', 'Developpement', 'Data'], 'Aout 2027', '10 semaines', 5100, 'https://picsum.photos/seed/alyra-2116/640/360', false),
  ('PRG-2117', 'prompt-engineering-pro', 'Prompt Engineering Pro', 'System prompts, evaluations et guardrails', array['IA', 'Product', 'Data'], 'Septembre 2027', '6 semaines', 2100, 'https://picsum.photos/seed/alyra-2117/640/360', false),
  ('PRG-2118', 'ai-blockchain-integration', 'AI + Blockchain Integration', 'Agents IA sur infrastructures decentralisees', array['IA', 'Developpement', 'Data'], 'Octobre 2027', '12 semaines', 6200, 'https://picsum.photos/seed/alyra-2118/640/360', false),
  ('PRG-2119', 'crypto-legal-essentials', 'Crypto Legal Essentials', 'Reglementation Europe, KYC et compliance', array['Blockchain', 'Gouvernance', 'Security'], 'Novembre 2027', '6 semaines', 2400, 'https://picsum.photos/seed/alyra-2119/640/360', false),
  ('PRG-2120', 'algo-trading-ai', 'Algo Trading & AI', 'Strategie data-driven sur marches crypto', array['IA', 'Finance', 'Data'], 'Decembre 2027', '14 semaines', 6900, 'https://picsum.photos/seed/alyra-2120/640/360', false)
on conflict (id) do update
set
  slug = excluded.slug,
  title = excluded.title,
  subtitle = excluded.subtitle,
  tags = excluded.tags,
  start_date_label = excluded.start_date_label,
  duration_label = excluded.duration_label,
  price_eur = excluded.price_eur,
  image_url = excluded.image_url,
  is_featured = excluded.is_featured,
  updated_at = now();

insert into public.program_pages (
  program_id,
  overview,
  overview_secondary,
  certification_title,
  certification_description,
  learning_path,
  professors
)
values
  ('PRG-2101', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent viverra, tortor vel euismod eleifend, nisi elit viverra purus, non congue sem quam in mauris.', 'Sed tincidunt, lacus ac faucibus ultrices, quam arcu pulvinar ipsum, nec tristique lacus erat sed lorem. Integer volutpat nunc vitae arcu tristique.', 'Certification Professionnelle Dev Blockchain', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vel molestie augue. Evaluation finale: projet, soutenance et QCM.', array['Module 1: Fondamentaux et cadrage du domaine.', 'Module 2: Outils, methodes et bonnes pratiques de production.', 'Module 3: Cas d''usage avances et ateliers diriges.', 'Module 4: Projet fil rouge et soutenance finale.'], '[{"name":"Nadia Renaud","role":"Lead Instructor","bio":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer euismod nibh non cursus convallis."},{"name":"Thomas Benali","role":"Expert Technique","bio":"Sed vitae nibh consequat, interdum orci vitae, posuere ipsum. Vivamus non purus ac nisi tempus sodales."},{"name":"Lea Marquet","role":"Mentor Projet","bio":"Vestibulum at nisl at leo sagittis molestie. Praesent tempus eros quis dui dignissim."}]'::jsonb),
  ('PRG-2102', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent viverra, tortor vel euismod eleifend, nisi elit viverra purus, non congue sem quam in mauris.', 'Sed tincidunt, lacus ac faucibus ultrices, quam arcu pulvinar ipsum, nec tristique lacus erat sed lorem. Integer volutpat nunc vitae arcu tristique.', 'Certification Professionnelle Expert Blockchain', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vel molestie augue. Evaluation finale: projet, soutenance et QCM.', array['Module 1: Fondamentaux et cadrage du domaine.', 'Module 2: Outils, methodes et bonnes pratiques de production.', 'Module 3: Cas d''usage avances et ateliers diriges.', 'Module 4: Projet fil rouge et soutenance finale.'], '[{"name":"Nadia Renaud","role":"Lead Instructor","bio":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer euismod nibh non cursus convallis."},{"name":"Thomas Benali","role":"Expert Technique","bio":"Sed vitae nibh consequat, interdum orci vitae, posuere ipsum. Vivamus non purus ac nisi tempus sodales."},{"name":"Lea Marquet","role":"Mentor Projet","bio":"Vestibulum at nisl at leo sagittis molestie. Praesent tempus eros quis dui dignissim."}]'::jsonb),
  ('PRG-2103', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent viverra, tortor vel euismod eleifend, nisi elit viverra purus, non congue sem quam in mauris.', 'Sed tincidunt, lacus ac faucibus ultrices, quam arcu pulvinar ipsum, nec tristique lacus erat sed lorem. Integer volutpat nunc vitae arcu tristique.', 'Certification Professionnelle Finance Decentralisee', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vel molestie augue. Evaluation finale: projet, soutenance et QCM.', array['Module 1: Fondamentaux et cadrage du domaine.', 'Module 2: Outils, methodes et bonnes pratiques de production.', 'Module 3: Cas d''usage avances et ateliers diriges.', 'Module 4: Projet fil rouge et soutenance finale.'], '[{"name":"Nadia Renaud","role":"Lead Instructor","bio":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer euismod nibh non cursus convallis."},{"name":"Thomas Benali","role":"Expert Technique","bio":"Sed vitae nibh consequat, interdum orci vitae, posuere ipsum. Vivamus non purus ac nisi tempus sodales."},{"name":"Lea Marquet","role":"Mentor Projet","bio":"Vestibulum at nisl at leo sagittis molestie. Praesent tempus eros quis dui dignissim."}]'::jsonb),
  ('PRG-2104', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent viverra, tortor vel euismod eleifend, nisi elit viverra purus, non congue sem quam in mauris.', 'Sed tincidunt, lacus ac faucibus ultrices, quam arcu pulvinar ipsum, nec tristique lacus erat sed lorem. Integer volutpat nunc vitae arcu tristique.', 'Certification Professionnelle Consultant Intelligence Artificielle', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vel molestie augue. Evaluation finale: projet, soutenance et QCM.', array['Module 1: Fondamentaux et cadrage du domaine.', 'Module 2: Outils, methodes et bonnes pratiques de production.', 'Module 3: Cas d''usage avances et ateliers diriges.', 'Module 4: Projet fil rouge et soutenance finale.'], '[{"name":"Nadia Renaud","role":"Lead Instructor","bio":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer euismod nibh non cursus convallis."},{"name":"Thomas Benali","role":"Expert Technique","bio":"Sed vitae nibh consequat, interdum orci vitae, posuere ipsum. Vivamus non purus ac nisi tempus sodales."},{"name":"Lea Marquet","role":"Mentor Projet","bio":"Vestibulum at nisl at leo sagittis molestie. Praesent tempus eros quis dui dignissim."}]'::jsonb),
  ('PRG-2105', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent viverra, tortor vel euismod eleifend, nisi elit viverra purus, non congue sem quam in mauris.', 'Sed tincidunt, lacus ac faucibus ultrices, quam arcu pulvinar ipsum, nec tristique lacus erat sed lorem. Integer volutpat nunc vitae arcu tristique.', 'Certification Professionnelle Developpeur Intelligence Artificielle', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vel molestie augue. Evaluation finale: projet, soutenance et QCM.', array['Module 1: Fondamentaux et cadrage du domaine.', 'Module 2: Outils, methodes et bonnes pratiques de production.', 'Module 3: Cas d''usage avances et ateliers diriges.', 'Module 4: Projet fil rouge et soutenance finale.'], '[{"name":"Nadia Renaud","role":"Lead Instructor","bio":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer euismod nibh non cursus convallis."},{"name":"Thomas Benali","role":"Expert Technique","bio":"Sed vitae nibh consequat, interdum orci vitae, posuere ipsum. Vivamus non purus ac nisi tempus sodales."},{"name":"Lea Marquet","role":"Mentor Projet","bio":"Vestibulum at nisl at leo sagittis molestie. Praesent tempus eros quis dui dignissim."}]'::jsonb),
  ('PRG-2106', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent viverra, tortor vel euismod eleifend, nisi elit viverra purus, non congue sem quam in mauris.', 'Sed tincidunt, lacus ac faucibus ultrices, quam arcu pulvinar ipsum, nec tristique lacus erat sed lorem. Integer volutpat nunc vitae arcu tristique.', 'Certification Professionnelle Smart Contract Security', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vel molestie augue. Evaluation finale: projet, soutenance et QCM.', array['Module 1: Fondamentaux et cadrage du domaine.', 'Module 2: Outils, methodes et bonnes pratiques de production.', 'Module 3: Cas d''usage avances et ateliers diriges.', 'Module 4: Projet fil rouge et soutenance finale.'], '[{"name":"Nadia Renaud","role":"Lead Instructor","bio":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer euismod nibh non cursus convallis."},{"name":"Thomas Benali","role":"Expert Technique","bio":"Sed vitae nibh consequat, interdum orci vitae, posuere ipsum. Vivamus non purus ac nisi tempus sodales."},{"name":"Lea Marquet","role":"Mentor Projet","bio":"Vestibulum at nisl at leo sagittis molestie. Praesent tempus eros quis dui dignissim."}]'::jsonb),
  ('PRG-2107', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent viverra, tortor vel euismod eleifend, nisi elit viverra purus, non congue sem quam in mauris.', 'Sed tincidunt, lacus ac faucibus ultrices, quam arcu pulvinar ipsum, nec tristique lacus erat sed lorem. Integer volutpat nunc vitae arcu tristique.', 'Certification Professionnelle Layer 2 Engineering', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vel molestie augue. Evaluation finale: projet, soutenance et QCM.', array['Module 1: Fondamentaux et cadrage du domaine.', 'Module 2: Outils, methodes et bonnes pratiques de production.', 'Module 3: Cas d''usage avances et ateliers diriges.', 'Module 4: Projet fil rouge et soutenance finale.'], '[{"name":"Nadia Renaud","role":"Lead Instructor","bio":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer euismod nibh non cursus convallis."},{"name":"Thomas Benali","role":"Expert Technique","bio":"Sed vitae nibh consequat, interdum orci vitae, posuere ipsum. Vivamus non purus ac nisi tempus sodales."},{"name":"Lea Marquet","role":"Mentor Projet","bio":"Vestibulum at nisl at leo sagittis molestie. Praesent tempus eros quis dui dignissim."}]'::jsonb),
  ('PRG-2108', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent viverra, tortor vel euismod eleifend, nisi elit viverra purus, non congue sem quam in mauris.', 'Sed tincidunt, lacus ac faucibus ultrices, quam arcu pulvinar ipsum, nec tristique lacus erat sed lorem. Integer volutpat nunc vitae arcu tristique.', 'Certification Professionnelle DAO Operations', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vel molestie augue. Evaluation finale: projet, soutenance et QCM.', array['Module 1: Fondamentaux et cadrage du domaine.', 'Module 2: Outils, methodes et bonnes pratiques de production.', 'Module 3: Cas d''usage avances et ateliers diriges.', 'Module 4: Projet fil rouge et soutenance finale.'], '[{"name":"Nadia Renaud","role":"Lead Instructor","bio":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer euismod nibh non cursus convallis."},{"name":"Thomas Benali","role":"Expert Technique","bio":"Sed vitae nibh consequat, interdum orci vitae, posuere ipsum. Vivamus non purus ac nisi tempus sodales."},{"name":"Lea Marquet","role":"Mentor Projet","bio":"Vestibulum at nisl at leo sagittis molestie. Praesent tempus eros quis dui dignissim."}]'::jsonb),
  ('PRG-2109', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent viverra, tortor vel euismod eleifend, nisi elit viverra purus, non congue sem quam in mauris.', 'Sed tincidunt, lacus ac faucibus ultrices, quam arcu pulvinar ipsum, nec tristique lacus erat sed lorem. Integer volutpat nunc vitae arcu tristique.', 'Certification Professionnelle Tokenomics Strategy', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vel molestie augue. Evaluation finale: projet, soutenance et QCM.', array['Module 1: Fondamentaux et cadrage du domaine.', 'Module 2: Outils, methodes et bonnes pratiques de production.', 'Module 3: Cas d''usage avances et ateliers diriges.', 'Module 4: Projet fil rouge et soutenance finale.'], '[{"name":"Nadia Renaud","role":"Lead Instructor","bio":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer euismod nibh non cursus convallis."},{"name":"Thomas Benali","role":"Expert Technique","bio":"Sed vitae nibh consequat, interdum orci vitae, posuere ipsum. Vivamus non purus ac nisi tempus sodales."},{"name":"Lea Marquet","role":"Mentor Projet","bio":"Vestibulum at nisl at leo sagittis molestie. Praesent tempus eros quis dui dignissim."}]'::jsonb),
  ('PRG-2110', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent viverra, tortor vel euismod eleifend, nisi elit viverra purus, non congue sem quam in mauris.', 'Sed tincidunt, lacus ac faucibus ultrices, quam arcu pulvinar ipsum, nec tristique lacus erat sed lorem. Integer volutpat nunc vitae arcu tristique.', 'Certification Professionnelle Web3 Fullstack', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vel molestie augue. Evaluation finale: projet, soutenance et QCM.', array['Module 1: Fondamentaux et cadrage du domaine.', 'Module 2: Outils, methodes et bonnes pratiques de production.', 'Module 3: Cas d''usage avances et ateliers diriges.', 'Module 4: Projet fil rouge et soutenance finale.'], '[{"name":"Nadia Renaud","role":"Lead Instructor","bio":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer euismod nibh non cursus convallis."},{"name":"Thomas Benali","role":"Expert Technique","bio":"Sed vitae nibh consequat, interdum orci vitae, posuere ipsum. Vivamus non purus ac nisi tempus sodales."},{"name":"Lea Marquet","role":"Mentor Projet","bio":"Vestibulum at nisl at leo sagittis molestie. Praesent tempus eros quis dui dignissim."}]'::jsonb),
  ('PRG-2111', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent viverra, tortor vel euismod eleifend, nisi elit viverra purus, non congue sem quam in mauris.', 'Sed tincidunt, lacus ac faucibus ultrices, quam arcu pulvinar ipsum, nec tristique lacus erat sed lorem. Integer volutpat nunc vitae arcu tristique.', 'Certification Professionnelle Data Analyst On-Chain', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vel molestie augue. Evaluation finale: projet, soutenance et QCM.', array['Module 1: Fondamentaux et cadrage du domaine.', 'Module 2: Outils, methodes et bonnes pratiques de production.', 'Module 3: Cas d''usage avances et ateliers diriges.', 'Module 4: Projet fil rouge et soutenance finale.'], '[{"name":"Nadia Renaud","role":"Lead Instructor","bio":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer euismod nibh non cursus convallis."},{"name":"Thomas Benali","role":"Expert Technique","bio":"Sed vitae nibh consequat, interdum orci vitae, posuere ipsum. Vivamus non purus ac nisi tempus sodales."},{"name":"Lea Marquet","role":"Mentor Projet","bio":"Vestibulum at nisl at leo sagittis molestie. Praesent tempus eros quis dui dignissim."}]'::jsonb),
  ('PRG-2112', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent viverra, tortor vel euismod eleifend, nisi elit viverra purus, non congue sem quam in mauris.', 'Sed tincidunt, lacus ac faucibus ultrices, quam arcu pulvinar ipsum, nec tristique lacus erat sed lorem. Integer volutpat nunc vitae arcu tristique.', 'Certification Professionnelle Blockchain for Finance', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vel molestie augue. Evaluation finale: projet, soutenance et QCM.', array['Module 1: Fondamentaux et cadrage du domaine.', 'Module 2: Outils, methodes et bonnes pratiques de production.', 'Module 3: Cas d''usage avances et ateliers diriges.', 'Module 4: Projet fil rouge et soutenance finale.'], '[{"name":"Nadia Renaud","role":"Lead Instructor","bio":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer euismod nibh non cursus convallis."},{"name":"Thomas Benali","role":"Expert Technique","bio":"Sed vitae nibh consequat, interdum orci vitae, posuere ipsum. Vivamus non purus ac nisi tempus sodales."},{"name":"Lea Marquet","role":"Mentor Projet","bio":"Vestibulum at nisl at leo sagittis molestie. Praesent tempus eros quis dui dignissim."}]'::jsonb),
  ('PRG-2113', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent viverra, tortor vel euismod eleifend, nisi elit viverra purus, non congue sem quam in mauris.', 'Sed tincidunt, lacus ac faucibus ultrices, quam arcu pulvinar ipsum, nec tristique lacus erat sed lorem. Integer volutpat nunc vitae arcu tristique.', 'Certification Professionnelle Generative AI Studio', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vel molestie augue. Evaluation finale: projet, soutenance et QCM.', array['Module 1: Fondamentaux et cadrage du domaine.', 'Module 2: Outils, methodes et bonnes pratiques de production.', 'Module 3: Cas d''usage avances et ateliers diriges.', 'Module 4: Projet fil rouge et soutenance finale.'], '[{"name":"Nadia Renaud","role":"Lead Instructor","bio":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer euismod nibh non cursus convallis."},{"name":"Thomas Benali","role":"Expert Technique","bio":"Sed vitae nibh consequat, interdum orci vitae, posuere ipsum. Vivamus non purus ac nisi tempus sodales."},{"name":"Lea Marquet","role":"Mentor Projet","bio":"Vestibulum at nisl at leo sagittis molestie. Praesent tempus eros quis dui dignissim."}]'::jsonb),
  ('PRG-2114', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent viverra, tortor vel euismod eleifend, nisi elit viverra purus, non congue sem quam in mauris.', 'Sed tincidunt, lacus ac faucibus ultrices, quam arcu pulvinar ipsum, nec tristique lacus erat sed lorem. Integer volutpat nunc vitae arcu tristique.', 'Certification Professionnelle AI Governance & Ethics', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vel molestie augue. Evaluation finale: projet, soutenance et QCM.', array['Module 1: Fondamentaux et cadrage du domaine.', 'Module 2: Outils, methodes et bonnes pratiques de production.', 'Module 3: Cas d''usage avances et ateliers diriges.', 'Module 4: Projet fil rouge et soutenance finale.'], '[{"name":"Nadia Renaud","role":"Lead Instructor","bio":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer euismod nibh non cursus convallis."},{"name":"Thomas Benali","role":"Expert Technique","bio":"Sed vitae nibh consequat, interdum orci vitae, posuere ipsum. Vivamus non purus ac nisi tempus sodales."},{"name":"Lea Marquet","role":"Mentor Projet","bio":"Vestibulum at nisl at leo sagittis molestie. Praesent tempus eros quis dui dignissim."}]'::jsonb),
  ('PRG-2115', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent viverra, tortor vel euismod eleifend, nisi elit viverra purus, non congue sem quam in mauris.', 'Sed tincidunt, lacus ac faucibus ultrices, quam arcu pulvinar ipsum, nec tristique lacus erat sed lorem. Integer volutpat nunc vitae arcu tristique.', 'Certification Professionnelle AI for Product Managers', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vel molestie augue. Evaluation finale: projet, soutenance et QCM.', array['Module 1: Fondamentaux et cadrage du domaine.', 'Module 2: Outils, methodes et bonnes pratiques de production.', 'Module 3: Cas d''usage avances et ateliers diriges.', 'Module 4: Projet fil rouge et soutenance finale.'], '[{"name":"Nadia Renaud","role":"Lead Instructor","bio":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer euismod nibh non cursus convallis."},{"name":"Thomas Benali","role":"Expert Technique","bio":"Sed vitae nibh consequat, interdum orci vitae, posuere ipsum. Vivamus non purus ac nisi tempus sodales."},{"name":"Lea Marquet","role":"Mentor Projet","bio":"Vestibulum at nisl at leo sagittis molestie. Praesent tempus eros quis dui dignissim."}]'::jsonb),
  ('PRG-2116', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent viverra, tortor vel euismod eleifend, nisi elit viverra purus, non congue sem quam in mauris.', 'Sed tincidunt, lacus ac faucibus ultrices, quam arcu pulvinar ipsum, nec tristique lacus erat sed lorem. Integer volutpat nunc vitae arcu tristique.', 'Certification Professionnelle Cloud for AI Systems', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vel molestie augue. Evaluation finale: projet, soutenance et QCM.', array['Module 1: Fondamentaux et cadrage du domaine.', 'Module 2: Outils, methodes et bonnes pratiques de production.', 'Module 3: Cas d''usage avances et ateliers diriges.', 'Module 4: Projet fil rouge et soutenance finale.'], '[{"name":"Nadia Renaud","role":"Lead Instructor","bio":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer euismod nibh non cursus convallis."},{"name":"Thomas Benali","role":"Expert Technique","bio":"Sed vitae nibh consequat, interdum orci vitae, posuere ipsum. Vivamus non purus ac nisi tempus sodales."},{"name":"Lea Marquet","role":"Mentor Projet","bio":"Vestibulum at nisl at leo sagittis molestie. Praesent tempus eros quis dui dignissim."}]'::jsonb),
  ('PRG-2117', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent viverra, tortor vel euismod eleifend, nisi elit viverra purus, non congue sem quam in mauris.', 'Sed tincidunt, lacus ac faucibus ultrices, quam arcu pulvinar ipsum, nec tristique lacus erat sed lorem. Integer volutpat nunc vitae arcu tristique.', 'Certification Professionnelle Prompt Engineering Pro', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vel molestie augue. Evaluation finale: projet, soutenance et QCM.', array['Module 1: Fondamentaux et cadrage du domaine.', 'Module 2: Outils, methodes et bonnes pratiques de production.', 'Module 3: Cas d''usage avances et ateliers diriges.', 'Module 4: Projet fil rouge et soutenance finale.'], '[{"name":"Nadia Renaud","role":"Lead Instructor","bio":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer euismod nibh non cursus convallis."},{"name":"Thomas Benali","role":"Expert Technique","bio":"Sed vitae nibh consequat, interdum orci vitae, posuere ipsum. Vivamus non purus ac nisi tempus sodales."},{"name":"Lea Marquet","role":"Mentor Projet","bio":"Vestibulum at nisl at leo sagittis molestie. Praesent tempus eros quis dui dignissim."}]'::jsonb),
  ('PRG-2118', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent viverra, tortor vel euismod eleifend, nisi elit viverra purus, non congue sem quam in mauris.', 'Sed tincidunt, lacus ac faucibus ultrices, quam arcu pulvinar ipsum, nec tristique lacus erat sed lorem. Integer volutpat nunc vitae arcu tristique.', 'Certification Professionnelle AI + Blockchain Integration', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vel molestie augue. Evaluation finale: projet, soutenance et QCM.', array['Module 1: Fondamentaux et cadrage du domaine.', 'Module 2: Outils, methodes et bonnes pratiques de production.', 'Module 3: Cas d''usage avances et ateliers diriges.', 'Module 4: Projet fil rouge et soutenance finale.'], '[{"name":"Nadia Renaud","role":"Lead Instructor","bio":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer euismod nibh non cursus convallis."},{"name":"Thomas Benali","role":"Expert Technique","bio":"Sed vitae nibh consequat, interdum orci vitae, posuere ipsum. Vivamus non purus ac nisi tempus sodales."},{"name":"Lea Marquet","role":"Mentor Projet","bio":"Vestibulum at nisl at leo sagittis molestie. Praesent tempus eros quis dui dignissim."}]'::jsonb),
  ('PRG-2119', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent viverra, tortor vel euismod eleifend, nisi elit viverra purus, non congue sem quam in mauris.', 'Sed tincidunt, lacus ac faucibus ultrices, quam arcu pulvinar ipsum, nec tristique lacus erat sed lorem. Integer volutpat nunc vitae arcu tristique.', 'Certification Professionnelle Crypto Legal Essentials', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vel molestie augue. Evaluation finale: projet, soutenance et QCM.', array['Module 1: Fondamentaux et cadrage du domaine.', 'Module 2: Outils, methodes et bonnes pratiques de production.', 'Module 3: Cas d''usage avances et ateliers diriges.', 'Module 4: Projet fil rouge et soutenance finale.'], '[{"name":"Nadia Renaud","role":"Lead Instructor","bio":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer euismod nibh non cursus convallis."},{"name":"Thomas Benali","role":"Expert Technique","bio":"Sed vitae nibh consequat, interdum orci vitae, posuere ipsum. Vivamus non purus ac nisi tempus sodales."},{"name":"Lea Marquet","role":"Mentor Projet","bio":"Vestibulum at nisl at leo sagittis molestie. Praesent tempus eros quis dui dignissim."}]'::jsonb),
  ('PRG-2120', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent viverra, tortor vel euismod eleifend, nisi elit viverra purus, non congue sem quam in mauris.', 'Sed tincidunt, lacus ac faucibus ultrices, quam arcu pulvinar ipsum, nec tristique lacus erat sed lorem. Integer volutpat nunc vitae arcu tristique.', 'Certification Professionnelle Algo Trading & AI', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vel molestie augue. Evaluation finale: projet, soutenance et QCM.', array['Module 1: Fondamentaux et cadrage du domaine.', 'Module 2: Outils, methodes et bonnes pratiques de production.', 'Module 3: Cas d''usage avances et ateliers diriges.', 'Module 4: Projet fil rouge et soutenance finale.'], '[{"name":"Nadia Renaud","role":"Lead Instructor","bio":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer euismod nibh non cursus convallis."},{"name":"Thomas Benali","role":"Expert Technique","bio":"Sed vitae nibh consequat, interdum orci vitae, posuere ipsum. Vivamus non purus ac nisi tempus sodales."},{"name":"Lea Marquet","role":"Mentor Projet","bio":"Vestibulum at nisl at leo sagittis molestie. Praesent tempus eros quis dui dignissim."}]'::jsonb)
on conflict (program_id) do update
set
  overview = excluded.overview,
  overview_secondary = excluded.overview_secondary,
  certification_title = excluded.certification_title,
  certification_description = excluded.certification_description,
  learning_path = excluded.learning_path,
  professors = excluded.professors,
  updated_at = now();

commit;
