export const catalogPrograms = [
  {
    id: "PRG-2101",
    slug: "dev-blockchain",
    title: "Dev Blockchain",
    subtitle: "Construire des dApps et smart contracts en production",
    tags: ["Blockchain", "Developpement", "Security"],
    date: "Mai 2026",
    duration: "14 semaines",
    price: 6200,
    image: "https://picsum.photos/seed/alyra-2101/640/360",
    featured: true,
  },
  {
    id: "PRG-2102",
    slug: "expert-blockchain",
    title: "Expert Blockchain",
    subtitle: "Architecture protocoles, L1/L2 et securite avancee",
    tags: ["Blockchain", "Security", "Gouvernance"],
    date: "Juin 2026",
    duration: "18 semaines",
    price: 7600,
    image: "https://picsum.photos/seed/alyra-2102/640/360",
    featured: true,
  },
  {
    id: "PRG-2103",
    slug: "finance-decentralisee",
    title: "Finance Decentralisee",
    subtitle: "Lending, AMM, tokenisation et gestion des risques",
    tags: ["Blockchain", "Finance", "Product"],
    date: "Juillet 2026",
    duration: "12 semaines",
    price: 4900,
    image: "https://picsum.photos/seed/alyra-2103/640/360",
    featured: true,
  },
  {
    id: "PRG-2104",
    slug: "consultant-intelligence-artificielle",
    title: "Consultant Intelligence Artificielle",
    subtitle: "Cadrage IA, roadmap et transformation metier",
    tags: ["IA", "Product", "Data"],
    date: "Aout 2026",
    duration: "10 semaines",
    price: 3900,
    image: "https://picsum.photos/seed/alyra-2104/640/360",
    featured: true,
  },
  {
    id: "PRG-2105",
    slug: "developpeur-intelligence-artificielle",
    title: "Developpeur Intelligence Artificielle",
    subtitle: "ML engineering, MLOps et applications generatives",
    tags: ["IA", "Developpement", "Data"],
    date: "Septembre 2026",
    duration: "16 semaines",
    price: 6900,
    image: "https://picsum.photos/seed/alyra-2105/640/360",
    featured: true,
  },
  {
    id: "PRG-2106",
    slug: "smart-contract-security",
    title: "Smart Contract Security",
    subtitle: "Audit, tests d'intrusion et securisation Solidity",
    tags: ["Blockchain", "Security", "Developpement"],
    date: "Octobre 2026",
    duration: "8 semaines",
    price: 3400,
    image: "https://picsum.photos/seed/alyra-2106/640/360",
  },
  {
    id: "PRG-2107",
    slug: "layer-2-engineering",
    title: "Layer 2 Engineering",
    subtitle: "Scalabilite Ethereum, rollups et interop",
    tags: ["Blockchain", "Developpement", "Security"],
    date: "Novembre 2026",
    duration: "12 semaines",
    price: 5600,
    image: "https://picsum.photos/seed/alyra-2107/640/360",
  },
  {
    id: "PRG-2108",
    slug: "dao-operations",
    title: "DAO Operations",
    subtitle: "Gouvernance, operations et outillage communautaire",
    tags: ["Blockchain", "Gouvernance", "Product"],
    date: "Decembre 2026",
    duration: "8 semaines",
    price: 3200,
    image: "https://picsum.photos/seed/alyra-2108/640/360",
  },
  {
    id: "PRG-2109",
    slug: "tokenomics-strategy",
    title: "Tokenomics Strategy",
    subtitle: "Modeles economiques, incentives et gouvernance",
    tags: ["Blockchain", "Finance", "Gouvernance"],
    date: "Janvier 2027",
    duration: "6 semaines",
    price: 2600,
    image: "https://picsum.photos/seed/alyra-2109/640/360",
  },
  {
    id: "PRG-2110",
    slug: "web3-fullstack",
    title: "Web3 Fullstack",
    subtitle: "Front React, wallets et donnees on-chain",
    tags: ["Blockchain", "Developpement", "Product"],
    date: "Fevrier 2027",
    duration: "14 semaines",
    price: 6400,
    image: "https://picsum.photos/seed/alyra-2110/640/360",
  },
  {
    id: "PRG-2111",
    slug: "data-analyst-on-chain",
    title: "Data Analyst On-Chain",
    subtitle: "Monitoring protocoles et analytics blockchain",
    tags: ["Blockchain", "Data", "Product"],
    date: "Mars 2027",
    duration: "8 semaines",
    price: 3300,
    image: "https://picsum.photos/seed/alyra-2111/640/360",
  },
  {
    id: "PRG-2112",
    slug: "blockchain-for-finance",
    title: "Blockchain for Finance",
    subtitle: "Tokenisation d'actifs et usages institutionnels",
    tags: ["Blockchain", "Finance", "Data"],
    date: "Avril 2027",
    duration: "10 semaines",
    price: 4600,
    image: "https://picsum.photos/seed/alyra-2112/640/360",
  },
  {
    id: "PRG-2113",
    slug: "generative-ai-studio",
    title: "Generative AI Studio",
    subtitle: "RAG, agents IA et applications metier",
    tags: ["IA", "Developpement", "Data"],
    date: "Mai 2027",
    duration: "10 semaines",
    price: 4900,
    image: "https://picsum.photos/seed/alyra-2113/640/360",
  },
  {
    id: "PRG-2114",
    slug: "ai-governance-ethics",
    title: "AI Governance & Ethics",
    subtitle: "Conformite, risque et cadre de gouvernance IA",
    tags: ["IA", "Gouvernance", "Security"],
    date: "Juin 2027",
    duration: "6 semaines",
    price: 2800,
    image: "https://picsum.photos/seed/alyra-2114/640/360",
  },
  {
    id: "PRG-2115",
    slug: "ai-for-product-managers",
    title: "AI for Product Managers",
    subtitle: "Pilotage de produits IA et mesure de valeur",
    tags: ["IA", "Product", "Data"],
    date: "Juillet 2027",
    duration: "6 semaines",
    price: 2500,
    image: "https://picsum.photos/seed/alyra-2115/640/360",
  },
  {
    id: "PRG-2116",
    slug: "cloud-for-ai-systems",
    title: "Cloud for AI Systems",
    subtitle: "Architecture cloud, couts et observabilite",
    tags: ["IA", "Developpement", "Data"],
    date: "Aout 2027",
    duration: "10 semaines",
    price: 5100,
    image: "https://picsum.photos/seed/alyra-2116/640/360",
  },
  {
    id: "PRG-2117",
    slug: "prompt-engineering-pro",
    title: "Prompt Engineering Pro",
    subtitle: "System prompts, evaluations et guardrails",
    tags: ["IA", "Product", "Data"],
    date: "Septembre 2027",
    duration: "6 semaines",
    price: 2100,
    image: "https://picsum.photos/seed/alyra-2117/640/360",
  },
  {
    id: "PRG-2118",
    slug: "ai-blockchain-integration",
    title: "AI + Blockchain Integration",
    subtitle: "Agents IA sur infrastructures decentralisees",
    tags: ["IA", "Developpement", "Data"],
    date: "Octobre 2027",
    duration: "12 semaines",
    price: 6200,
    image: "https://picsum.photos/seed/alyra-2118/640/360",
  },
  {
    id: "PRG-2119",
    slug: "crypto-legal-essentials",
    title: "Crypto Legal Essentials",
    subtitle: "Reglementation Europe, KYC et compliance",
    tags: ["Blockchain", "Gouvernance", "Security"],
    date: "Novembre 2027",
    duration: "6 semaines",
    price: 2400,
    image: "https://picsum.photos/seed/alyra-2119/640/360",
  },
  {
    id: "PRG-2120",
    slug: "algo-trading-ai",
    title: "Algo Trading & AI",
    subtitle: "Strategie data-driven sur marches crypto",
    tags: ["IA", "Finance", "Data"],
    date: "Decembre 2027",
    duration: "14 semaines",
    price: 6900,
    image: "https://picsum.photos/seed/alyra-2120/640/360",
  },
];

export const priceBuckets = [
  { id: "low", label: "< 3000 EUR", test: (price) => price < 3000 },
  {
    id: "mid",
    label: "3000 EUR - 5000 EUR",
    test: (price) => price >= 3000 && price <= 5000,
  },
  { id: "high", label: "> 5000 EUR", test: (price) => price > 5000 },
];

export const featuredPrograms = catalogPrograms.filter((item) => item.featured);
